--- 
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
jdk: oraclejdk8
#install: "gradle assemble"
language: android
android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
   - tools
   - platform-tools

  # The BuildTools version used by your project
  - build-tools-26.0.2

  # The SDK version used to compile your project
  - android-28

  # Additional components
 # - extra-google-google_play_services

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  #- sys-img-x86-android-26
  #- sys-img-armeabi-v7a-android-17
notifications: 
  on_failure: always
  on_success: change
  slack: "sylergy:TEISIyT2e0IR6z2ZDFlqNUTH"
script: "./gradlew build connectedCheck"
sudo: false
