--- 
jdk: oraclejdk8
language: android
android: 
  components: 
    - tools
    - build-tools-26.0.2
    - platform-tools
    - android-23
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - extra-google-google_play_services
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
before_install:
  - yes | sdkmanager "platforms;android-28"

before_cache: 
  - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
  - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache: 
  directories: 
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
notifications: 
  on_failure: always
  on_success: change
  slack: "sylergy:TEISIyT2e0IR6z2ZDFlqNUTH"
script: "./gradlew build connectedCheck"
sudo: false
